//description html
const descrition = {
    "Fitoftora_fase_1_Colonización": ['<h2>Fitóftora fase 1 - Colonización</h2>','<h3 class="text-2xl font-semibold mb-2">Medidas de manejo</h3><ul class="list-disc list-inside mb-4"><li class="mb-1">Eliminación de plantas infectadas.</li><li class="mb-1">Evitar el encharcamiento de agua alrededor de la planta.</li><li class="mb-1">Verificar la sombra en el cultivo de cacao.</li></ul><div class="bg-white p-4 "><h3 class="text-xl font-semibold mb-2">Tratamiento de fungicidas para aplicar en los cultivos de cacao </h3><p><strong>Aplicar:</strong> sulfato de cobre - Diss zeus</p><p><strong>Dosis:</strong> 2.5kg/ha</p><p><strong>Tiempo:</strong> 10- 14 dias</p><p><strong>Aplicación:</strong> En la raiz y tallo de la planta</p></div>'],


    "Fitoftora_fase_2_Reproducción": ["<h2>Fitóftora fase 2 - Reproducción</h2>",'<h3 class="text-2xl font-semibold mb-2">Medidas de manejo</h3><ul class="list-disc list-inside mb-4"><li class="mb-1">Remover la maleza</li><li class="mb-1">Utilizar agua de riego limpia y evitar el exceso de humedad en el suelo</li><li class="mb-1">Evitar el riego por aspersión y en su lugar, utilizar métodos de riego por goteo para reducir la humedad foliar y prevenir la propagación</li><li class="mb-1">Eliminación de frutos enfermos o caídos</li></ul><div class="bg-white p-4"><h3 class="text-xl font-semibold mb-2">Tratamiento de fungicidas para aplicar en los cultivos de cacao</h3><p><strong>Aplicar:</strong> sulfato de cobre - Diss zeus</p><p><strong>Dosis:</strong> 0.6 lit/ha</p><p><strong>Tiempo:</strong> 7-14 días</p><p><strong>Aplicación:</strong> alrededor de las hojas y suelo</p><p><strong>Aplicar:</strong> Azoxistrobina - Bankit</p><p><strong>Dosis:</strong> 0.4 lit/ha</p><p><strong>Tiempo:</strong> 10-14 días</p><p><strong>Aplicación:</strong> En el suelo por medio de aspersores</p></div>'],
    

    "Sano": ["<h2>Cacao sano</h2>",'<div><span>Un cacao sano es un fruto que se desarrolla adecuadamente sin mostrar signos de enfermedades, plagas o deficiencias nutricionales. Aquí tienes una descripción detallada de las características de un cacao sano:</span><br><b>Características de un Cacao Sano:</b><br><b>Apariencia del Fruto:</b><ul><li><span>Color Uniforme: El fruto del cacao, conocido como mazorca, debe tener un color uniforme acorde a su variedad y estado de madurez. Esto puede variar desde verde para frutos inmaduros hasta amarillo, rojo o naranja para frutos maduros, dependiendo de la variedad.</span></li><li><span>Superficie Lisa: La cáscara del fruto debe ser lisa y sin manchas, cicatrices, o lesiones. No debe haber presencia de manchas blancas, amarillas, o negras que podrían indicar enfermedades como la Moniliasis o la Escoba de Bruja.</span></li></ul><b>Tamaño y Forma:</b><ul><li><span>Desarrollo Completo: El fruto debe tener un tamaño y forma adecuada para su variedad, indicando un desarrollo completo y saludable. Las mazorcas deformadas o subdesarrolladas pueden indicar problemas nutricionales o estrés en la planta.</span></li><li><span>Simetría: Las mazorcas deben ser simétricas, sin abultamientos ni deformidades.</span></li></ul><b>Textura:</b><ul><li><span>Firmeza: La cáscara debe ser firme al tacto, sin partes blandas o necrosadas que podrían indicar pudrición o infecciones fúngicas.</span></li><li><span>Sin Grietas: La superficie no debe tener grietas ni aberturas que puedan servir como puntos de entrada para patógenos.</span></li></ul></div>']


};
